using System.Collections;
using YamlDotNet.Core;
using YamlDotNet.Serialization;
using YamlDotNet.Serialization.NamingConventions;

namespace ForgeTrust.AppSurface.Release;

/// <summary>
/// Mutable YAML sidecar metadata for release-note documentation pages.
/// </summary>
/// <remarks>
/// Sidecars are dictionary-backed so unknown fields are preserved. The committed release artifact remains in the
/// <c>prepared</c> state; only a tag-bound resolver creates the transient <c>tagged</c> projection used by docs and publishing.
/// </remarks>
internal sealed class ReleaseSidecar
{
    private readonly Dictionary<object, object?> _metadata;

    private ReleaseSidecar(Dictionary<object, object?> metadata)
    {
        _metadata = metadata;
    }

    /// <summary>
    /// Loads sidecar metadata from YAML.
    /// </summary>
    /// <param name="path">Sidecar path. Expected content is a YAML mapping at the document root.</param>
    /// <param name="cancellationToken">Cancellation token honored during file I/O.</param>
    /// <returns>Loaded sidecar whose unknown keys are preserved for later serialization.</returns>
    /// <remarks>
    /// The current release flow expects the unreleased sidecar to contain documentation keys such as <c>title</c>, <c>summary</c>,
    /// <c>page_type</c>, <c>nav_group</c>, <c>order</c>, <c>breadcrumbs</c>, and <c>trust</c>. Missing keys are tolerated because
    /// <see cref="ToPreparedRelease"/> writes the release-owned fields. Malformed YAML is wrapped in <see cref="ReleaseToolException"/>
    /// with <c>release-sidecar-invalid</c>; I/O and cancellation failures bubble to the shared command diagnostic layer.
    /// </remarks>
    internal static async Task<ReleaseSidecar> LoadAsync(string path, CancellationToken cancellationToken)
    {
        var content = await File.ReadAllTextAsync(path, cancellationToken);
        Dictionary<object, object?> metadata;
        try
        {
            metadata = new DeserializerBuilder().Build().Deserialize<Dictionary<object, object?>>(content)
                ?? [];
        }
        catch (YamlException ex)
        {
            throw new ReleaseToolException(ReleaseDiagnostic.Error(
                "release-sidecar-invalid",
                "Release sidecar metadata is not valid YAML.",
                $"The sidecar at `{path}` could not be parsed: {ex.Message}",
                "Fix the YAML syntax in the sidecar before preparing the release.",
                "tools/ForgeTrust.AppSurface.Release/README.md#prepare"));
        }

        return new ReleaseSidecar(metadata);
    }

    /// <summary>
    /// Converts unreleased metadata into a committed prepared-release sidecar.
    /// </summary>
    /// <param name="version">Prepared release version.</param>
    /// <param name="date">Preparation date.</param>
    /// <returns>Prepared release sidecar YAML using underscored key naming for generated CLR-backed values.</returns>
    /// <remarks>
    /// This method mutates the loaded dictionary before serializing. It replaces release-owned metadata with provisional
    /// prepared-release values and preserves unrelated keys from the source sidecar. The result deliberately makes no
    /// tag-derived or GitHub Release existence claim.
    /// </remarks>
    internal string ToPreparedRelease(SemVer version, DateOnly date)
    {
        _metadata["title"] = $"Release {version}";
        _metadata["summary"] = $"Coordinated AppSurface release {version}, prepared on {date:yyyy-MM-dd} for maintainer review.";
        _metadata["order"] = 10;
        _metadata["breadcrumbs"] = new[] { "Releases", $"v{version}" };
        _metadata["release"] = new Dictionary<string, object?>
        {
            ["schema"] = "appsurface-release-sidecar-v1",
            ["state"] = "prepared",
            ["id"] = version.TagName
        };
        _metadata["trust"] = new Dictionary<string, object?>
        {
            ["status"] = "Prepared",
            ["summary"] = $"This release sidecar is prepared for maintainer review and is not yet tag-backed for AppSurface {version}.",
            ["freshness"] = $"Prepared on {date:yyyy-MM-dd}. Treat it as provisional until its verified annotated tag exists.",
            ["change_scope"] = "Repository-wide. Packages, CLI tooling, examples, and docs-facing behavior ship in one coordinated version.",
            ["archive"] = "The matching compact ledger entry lives in CHANGELOG.md.",
            ["sources"] = new[]
            {
                "Release artifacts were generated by ./eng/release prepare.",
                "Package release note paths are recorded in packages/package-index.yml.",
                "Final tagged metadata is derived only from a verified annotated tag."
            }
        };

        return new SerializerBuilder()
            .WithNamingConvention(UnderscoredNamingConvention.Instance)
            .Build()
            .Serialize(_metadata);
    }

    /// <summary>
    /// Parses a sidecar YAML payload that was read from a tag or another explicit source.
    /// </summary>
    /// <param name="content">YAML document content.</param>
    /// <param name="source">Human-readable source identifier used in diagnostics.</param>
    /// <returns>Parsed release sidecar with unknown fields preserved.</returns>
    internal static ReleaseSidecar Parse(string content, string source)
    {
        Dictionary<object, object?> metadata;
        try
        {
            metadata = new DeserializerBuilder().Build().Deserialize<Dictionary<object, object?>>(content)
                ?? [];
        }
        catch (YamlException ex)
        {
            throw new ReleaseToolException(ReleaseDiagnostic.Error(
                "release-sidecar-invalid",
                "Release sidecar metadata is not valid YAML.",
                $"The sidecar from {source} could not be parsed: {ex.Message}",
                "Regenerate the prepared release sidecar instead of editing generated release metadata by hand.",
                "tools/ForgeTrust.AppSurface.Release/README.md#prepared-to-tagged-state"));
        }

        return new ReleaseSidecar(metadata);
    }

    /// <summary>
    /// Ensures that this sidecar is an explicit prepared artifact for the requested version.
    /// </summary>
    /// <param name="version">Release version that owns the sidecar.</param>
    /// <param name="source">Human-readable source identifier used in diagnostics.</param>
    /// <remarks>
    /// Missing state is treated as a legacy artifact rather than being silently interpreted as prepared. This keeps new release
    /// publication deterministic while leaving historical docs and archive reads independent of the new resolver.
    /// </remarks>
    internal void EnsurePrepared(SemVer version, string source)
    {
        var release = GetMapping(_metadata, "release");
        if (release is null)
        {
            throw LegacyTagBindingUnsupported(source);
        }

        var schema = GetString(release, "schema");
        if (!string.Equals(schema, "appsurface-release-sidecar-v1", StringComparison.Ordinal))
        {
            throw new ReleaseToolException(ReleaseDiagnostic.Error(
                "release-sidecar-schema-invalid",
                "The release sidecar does not declare the supported prepared-to-tagged schema.",
                $"The sidecar from {source} declares release.schema: {schema ?? "<missing>"}.",
                "Regenerate the release PR with ./eng/release prepare so the versioned sidecar carries appsurface-release-sidecar-v1.",
                "tools/ForgeTrust.AppSurface.Release/README.md#prepared-to-tagged-state"));
        }

        var state = GetString(release, "state");
        if (state is null)
        {
            throw LegacyTagBindingUnsupported(source);
        }

        if (!string.Equals(state, "prepared", StringComparison.Ordinal))
        {
            throw new ReleaseToolException(ReleaseDiagnostic.Error(
                "release-sidecar-state-invalid",
                "The tagged release sidecar is not in the prepared source state.",
                $"The sidecar from {source} declares release.state: {state}.",
                "Regenerate the release PR with ./eng/release prepare; only the tag-bound projection may declare tagged.",
                "tools/ForgeTrust.AppSurface.Release/README.md#prepared-to-tagged-state"));
        }

        var releaseId = GetString(release, "id");
        if (!string.Equals(releaseId, version.TagName, StringComparison.Ordinal))
        {
            throw new ReleaseToolException(ReleaseDiagnostic.Error(
                "release-sidecar-id-mismatch",
                "The prepared release sidecar does not match the requested release version.",
                $"The sidecar from {source} declares release.id: {releaseId ?? "<missing>"}, but {version.TagName} was requested.",
                "Regenerate the release artifacts for the requested version and create a matching annotated tag.",
                "tools/ForgeTrust.AppSurface.Release/README.md#prepared-to-tagged-state"));
        }

        var trust = GetMapping(_metadata, "trust");
        var trustStatus = GetString(trust, "status");
        if (!string.Equals(trustStatus, "Prepared", StringComparison.Ordinal))
        {
            throw new ReleaseToolException(ReleaseDiagnostic.Error(
                "release-sidecar-final-claim-invalid",
                "The prepared release sidecar contains a final trust claim.",
                $"The sidecar from {source} declares trust.status: {trustStatus ?? "<missing>"}.",
                "Prepared source must use trust.status: Prepared; tagged wording is rendered only after tag binding validation.",
                "tools/ForgeTrust.AppSurface.Release/README.md#prepared-to-tagged-state"));
        }

        if (TryFindFinalTrustClaim(trust, out var finalClaim))
        {
            throw new ReleaseToolException(ReleaseDiagnostic.Error(
                "release-sidecar-final-claim-invalid",
                "The prepared release sidecar contains tagged-only trust wording.",
                $"The sidecar from {source} includes the final claim: {finalClaim}.",
                "Prepared source must not claim a final narrative, tag freshness, or GitHub Release publication; tagged wording is rendered only after tag binding validation.",
                "tools/ForgeTrust.AppSurface.Release/README.md#prepared-to-tagged-state"));
        }
    }

    /// <summary>
    /// Creates the transient tagged sidecar projection after a resolver has verified the annotated tag.
    /// </summary>
    /// <param name="version">Release version that owns the sidecar.</param>
    /// <param name="taggerTimestamp">Timestamp recorded in the annotated tag object.</param>
    /// <param name="source">Human-readable source identifier used for prepared-state validation.</param>
    /// <returns>Rendered tagged sidecar YAML. The caller owns any temporary output path.</returns>
    /// <remarks>
    /// This method mutates and consumes the loaded metadata. After projection, the instance declares <c>release.state: tagged</c>
    /// and final trust wording, so it no longer passes <see cref="EnsurePrepared"/>. Parse a fresh <see cref="ReleaseSidecar"/>
    /// for each projection.
    /// </remarks>
    internal string ToTaggedProjection(SemVer version, DateTimeOffset taggerTimestamp, string source)
    {
        EnsurePrepared(version, source);
        var taggedAtUtc = taggerTimestamp.ToUniversalTime();
        _metadata["release"] = new Dictionary<object, object?>
        {
            ["schema"] = "appsurface-release-sidecar-v1",
            ["state"] = "tagged",
            ["id"] = version.TagName
        };
        _metadata["title"] = $"Release {version}";
        _metadata["summary"] = $"Coordinated AppSurface release {version}, verified against annotated tag {version.TagName}.";
        _metadata["order"] = 10;
        _metadata["breadcrumbs"] = new[] { "Releases", $"v{version}" };
        _metadata["trust"] = new Dictionary<object, object?>
        {
            ["status"] = "Tagged",
            ["summary"] = $"This page is the final narrative release note for AppSurface {version}.",
            ["freshness"] = $"Tagged at {taggedAtUtc:O} after the release binding was verified.",
            ["change_scope"] = "Repository-wide. Packages, CLI tooling, examples, and docs-facing behavior ship in one coordinated version.",
            ["archive"] = "The matching compact ledger entry lives in CHANGELOG.md.",
            ["sources"] = new[]
            {
                $"Prepared artifacts and release evidence were verified against annotated tag {version.TagName}.",
                "GitHub Release publication is bound to that annotated tag."
            }
        };

        return new SerializerBuilder()
            .WithNamingConvention(UnderscoredNamingConvention.Instance)
            .Build()
            .Serialize(_metadata);
    }

    /// <summary>
    /// Creates reset unreleased metadata for the next release cycle.
    /// </summary>
    /// <returns>Canonical unreleased sidecar YAML with title, navigation, trust metadata, and source guidance.</returns>
    /// <remarks>
    /// The template is complete enough for docs harvesting without requiring the previous sidecar. It intentionally resets release-specific
    /// trust metadata back to provisional language.
    /// </remarks>
    internal static string UnreleasedTemplate()
    {
        return """
            release:
              schema: appsurface-release-sidecar-v1
              state: unreleased
            title: Unreleased
            summary: Living proof artifact for the next coordinated AppSurface release. This page is intentionally provisional until a version is tagged.
            page_type: release-note
            nav_group: Releases
            order: 15
            breadcrumbs:
              - Releases
              - Unreleased
            trust:
              status: Unreleased
              summary: This page tracks merged work that is intended for the next coordinated AppSurface release. The grouping and wording can still change before the tag is cut.
              freshness: Updated as changes land on main. Treat it as current but provisional.
              change_scope: Repository-wide. Packages, CLI tooling, examples, and docs-facing behavior all roll into the same next version.
              migration:
                label: Read the pre-1.0 upgrade policy
                href: /docs/releases/upgrade-policy
              archive: When a version is tagged, the final narrative moves into a versioned release note and the compact summary is recorded in CHANGELOG.md.
              sources:
                - Pull request titles follow Conventional Commits.
                - CHANGELOG.md is the compact ledger.
                - Tagged release notes carry the final migration narrative.
            """;
    }

    private static Dictionary<object, object?>? GetMapping(Dictionary<object, object?> metadata, string key)
    {
        return GetMapping((object?)metadata, key);
    }

    private static Dictionary<object, object?>? GetMapping(object? mapping, string key)
    {
        return GetValue(mapping, key) as Dictionary<object, object?>;
    }

    private static ReleaseToolException LegacyTagBindingUnsupported(string source)
    {
        return new ReleaseToolException(ReleaseDiagnostic.Error(
            "release-legacy-tag-binding-unsupported",
            "The release sidecar predates the prepared-to-tagged binding contract.",
            $"The sidecar from {source} does not declare release.state.",
            "Use the existing historical archive path for this tag. New inspect and publish operations require a release prepared after the binding contract was introduced.",
            "tools/ForgeTrust.AppSurface.Release/README.md#prepared-to-tagged-state"));
    }

    private static string? GetString(Dictionary<object, object?>? mapping, string key)
    {
        return GetValue(mapping, key) as string;
    }

    private static object? GetValue(object? mapping, string key)
    {
        if (mapping is not Dictionary<object, object?> dictionary)
        {
            return null;
        }

        foreach (var (candidateKey, value) in dictionary)
        {
            if (candidateKey is string candidate
                && string.Equals(candidate, key, StringComparison.Ordinal))
            {
                return value;
            }
        }

        return null;
    }

    private static bool TryFindFinalTrustClaim(Dictionary<object, object?>? trust, out string finalClaim)
    {
        foreach (var text in EnumerateStrings(trust))
        {
            if (text.Contains("final narrative", StringComparison.OrdinalIgnoreCase)
                || text.Contains("tagged at", StringComparison.OrdinalIgnoreCase)
                || text.Contains("verified against annotated tag", StringComparison.OrdinalIgnoreCase)
                || text.Contains("GitHub Release", StringComparison.OrdinalIgnoreCase))
            {
                finalClaim = text;
                return true;
            }
        }

        finalClaim = string.Empty;
        return false;
    }

    private static IEnumerable<string> EnumerateStrings(object? value)
    {
        if (value is string text)
        {
            yield return text;
            yield break;
        }

        if (value is Dictionary<object, object?> mapping)
        {
            foreach (var child in mapping.Values)
            {
                foreach (var nestedText in EnumerateStrings(child))
                {
                    yield return nestedText;
                }
            }

            yield break;
        }

        if (value is not IEnumerable values)
        {
            yield break;
        }

        foreach (var child in values)
        {
            foreach (var nestedText in EnumerateStrings(child))
            {
                yield return nestedText;
            }
        }
    }
}
