using YamlDotNet.Core;
using YamlDotNet.Serialization;
using YamlDotNet.Serialization.NamingConventions;

namespace ForgeTrust.AppSurface.Release;

/// <summary>
/// Mutable YAML sidecar metadata for release-note documentation pages.
/// </summary>
/// <remarks>
/// Sidecars are dictionary-backed so unknown fields are preserved. Tagged-release conversion overwrites release-owned keys
/// (<c>title</c>, <c>summary</c>, <c>order</c>, <c>breadcrumbs</c>, and <c>trust</c>) and leaves unrelated keys untouched.
/// </remarks>
internal sealed class ReleaseSidecar
{
    private readonly Dictionary<object, object?> _metadata;

    private ReleaseSidecar(Dictionary<object, object?> metadata)
    {
        _metadata = metadata;
    }

    /// <summary>
    /// Loads sidecar metadata from YAML.
    /// </summary>
    /// <param name="path">Sidecar path. Expected content is a YAML mapping at the document root.</param>
    /// <param name="cancellationToken">Cancellation token honored during file I/O.</param>
    /// <returns>Loaded sidecar whose unknown keys are preserved for later serialization.</returns>
    /// <remarks>
    /// The current release flow expects the unreleased sidecar to contain documentation keys such as <c>title</c>, <c>summary</c>,
    /// <c>page_type</c>, <c>nav_group</c>, <c>order</c>, <c>breadcrumbs</c>, and <c>trust</c>. Missing keys are tolerated because
    /// <see cref="ToTaggedRelease"/> writes the release-owned fields. Malformed YAML is wrapped in <see cref="ReleaseToolException"/>
    /// with <c>release-sidecar-invalid</c>; I/O and cancellation failures bubble to the shared command diagnostic layer.
    /// </remarks>
    internal static async Task<ReleaseSidecar> LoadAsync(string path, CancellationToken cancellationToken)
    {
        var content = await File.ReadAllTextAsync(path, cancellationToken);
        Dictionary<object, object?> metadata;
        try
        {
            metadata = new DeserializerBuilder().Build().Deserialize<Dictionary<object, object?>>(content)
                ?? [];
        }
        catch (YamlException ex)
        {
            throw new ReleaseToolException(ReleaseDiagnostic.Error(
                "release-sidecar-invalid",
                "Release sidecar metadata is not valid YAML.",
                $"The sidecar at `{path}` could not be parsed: {ex.Message}",
                "Fix the YAML syntax in the sidecar before preparing the release.",
                "tools/ForgeTrust.AppSurface.Release/README.md#prepare"));
        }

        return new ReleaseSidecar(metadata);
    }

    /// <summary>
    /// Converts unreleased metadata into tagged-release metadata.
    /// </summary>
    /// <param name="version">Tagged release version.</param>
    /// <param name="date">Release date.</param>
    /// <returns>Tagged release sidecar YAML using underscored key naming for generated CLR-backed values.</returns>
    /// <remarks>
    /// This method mutates the loaded dictionary before serializing. It replaces release-owned metadata with final tagged-release
    /// values and preserves unrelated keys from the source sidecar. Callers should not reuse the instance for another version after
    /// conversion.
    /// </remarks>
    internal string ToTaggedRelease(SemVer version, DateOnly date)
    {
        _metadata["title"] = $"Release {version}";
        _metadata["summary"] = $"Coordinated AppSurface release {version}, tagged on {date:yyyy-MM-dd}.";
        _metadata["order"] = 10;
        _metadata["breadcrumbs"] = new[] { "Releases", $"v{version}" };
        _metadata["trust"] = new Dictionary<string, object?>
        {
            ["status"] = "Tagged",
            ["summary"] = $"This page is the final narrative release note for AppSurface {version}.",
            ["freshness"] = $"Tagged on {date:yyyy-MM-dd}.",
            ["change_scope"] = "Repository-wide. Packages, CLI tooling, examples, and docs-facing behavior ship in one coordinated version.",
            ["archive"] = "The matching compact ledger entry lives in CHANGELOG.md.",
            ["sources"] = new[]
            {
                "Release artifacts were generated by ./eng/release prepare.",
                "Package release note paths are recorded in packages/package-index.yml.",
                "The GitHub Release is created from the annotated tag commit."
            }
        };

        return new SerializerBuilder()
            .WithNamingConvention(UnderscoredNamingConvention.Instance)
            .Build()
            .Serialize(_metadata);
    }

    /// <summary>
    /// Creates reset unreleased metadata for the next release cycle.
    /// </summary>
    /// <returns>Canonical unreleased sidecar YAML with title, navigation, trust metadata, and source guidance.</returns>
    /// <remarks>
    /// The template is complete enough for docs harvesting without requiring the previous sidecar. It intentionally resets release-specific
    /// trust metadata back to provisional language.
    /// </remarks>
    internal static string UnreleasedTemplate()
    {
        return """
            title: Unreleased
            summary: Living proof artifact for the next coordinated AppSurface release. This page is intentionally provisional until a version is tagged.
            page_type: release-note
            nav_group: Releases
            order: 15
            breadcrumbs:
              - Releases
              - Unreleased
            trust:
              status: Unreleased
              summary: This page tracks merged work that is intended for the next coordinated AppSurface release. The grouping and wording can still change before the tag is cut.
              freshness: Updated as changes land on main. Treat it as current but provisional.
              change_scope: Repository-wide. Packages, CLI tooling, examples, and docs-facing behavior all roll into the same next version.
              migration:
                label: Read the pre-1.0 upgrade policy
                href: /docs/releases/upgrade-policy
              archive: When a version is tagged, the final narrative moves into a versioned release note and the compact summary is recorded in CHANGELOG.md.
              sources:
                - Pull request titles follow Conventional Commits.
                - CHANGELOG.md is the compact ledger.
                - Tagged release notes carry the final migration narrative.
            """;
    }
}
