using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using CliFx;
using CliFx.Binding;
using CliFx.Infrastructure;
using ForgeTrust.AppSurface.Console;
using ForgeTrust.AppSurface.Core;
using Markdig;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using YamlDotNet.Core;
using YamlDotNet.Serialization;
using YamlDotNet.Serialization.NamingConventions;

namespace ForgeTrust.AppSurface.Release;

internal static class ReleaseNoteBuilder
{
    /// <summary>
    /// Converts the living unreleased note into a tagged release note.
    /// </summary>
    /// <param name="version">Release version.</param>
    /// <param name="date">Release date.</param>
    /// <param name="unreleased">Unreleased Markdown content.</param>
    /// <returns>Tagged release Markdown.</returns>
    internal static string Build(SemVer version, DateOnly date, string unreleased)
    {
        Markdown.Parse(unreleased);
        var body = Regex.Replace(unreleased, "^#\\s+Unreleased\\s*$", $"# Release {version}", RegexOptions.Multiline);
        body = body.Replace("living release note for the next coordinated AppSurface version", $"release note for AppSurface {version}", StringComparison.Ordinal);
        body = body.Replace("provisional until a tag is cut", $"finalized on {date:yyyy-MM-dd}", StringComparison.Ordinal);

        var header = $"""
            <!--
            Generated by ./eng/release prepare.
            Version: {version}
            Date: {date:yyyy-MM-dd}
            -->

            """;
        return header + body.TrimEnd() + Environment.NewLine;
    }

    /// <summary>
    /// Creates the next-cycle unreleased proof artifact.
    /// </summary>
    /// <param name="previousVersion">Version that just moved into tagged release files.</param>
    /// <returns>Reset unreleased Markdown.</returns>
    internal static string ResetUnreleased(SemVer previousVersion)
    {
        return $"""
            # Unreleased

            This is the living release note for the next coordinated AppSurface version after `{previousVersion}`. It stays provisional until the next tag is cut.

            ## What is taking shape

            - Add merged public changes here as they land.

            ## Included in the next coordinated version

            ### Release and docs surface

            - Add release-facing changes here.

            ## Migration watch

            - Record breaking or behavior-changing guidance here before it moves into the tagged release note.

            """;
    }
}
