using System.Text.RegularExpressions;
using Markdig;

namespace ForgeTrust.AppSurface.Release;

internal static class ReleaseNoteBuilder
{
    private sealed record UnreleasedTemplatePlaceholder(string Text, string Section);

    private const string TakingShapePlaceholder = "- Add merged public changes here as they land.";

    private const string IncludedChangesPlaceholder = "- Add release-facing changes here as they land.";

    private const string MigrationWatchPlaceholder =
        "- Record-breaking or behavior-changing guidance here before it moves into the tagged release note.";

    private static readonly UnreleasedTemplatePlaceholder[] UnreleasedTemplatePlaceholderDefinitions =
    [
        new(TakingShapePlaceholder, "taking-shape"),
        new(IncludedChangesPlaceholder, "included"),
        new(MigrationWatchPlaceholder, "migration-watch")
    ];

    /// <summary>
    /// Gets the reset-only placeholder bullets that must not appear in a tagged release note.
    /// </summary>
    internal static IReadOnlyList<string> UnreleasedTemplatePlaceholders { get; } =
    [
        TakingShapePlaceholder,
        IncludedChangesPlaceholder,
        MigrationWatchPlaceholder
    ];

    /// <summary>
    /// Converts the living unreleased note into a tagged release note.
    /// </summary>
    /// <param name="version">Release version rendered in the heading and generated comment.</param>
    /// <param name="date">Release date rendered with invariant <c>yyyy-MM-dd</c> formatting.</param>
    /// <param name="unreleased">Unreleased Markdown content. Canonical input starts with an exact <c># Unreleased</c> heading.</param>
    /// <returns>Tagged release Markdown with a generated comment header and a trailing newline.</returns>
    /// <remarks>
    /// The method first parses Markdown to catch syntax problems, but it does not use the returned syntax tree to rewrite content.
    /// It then replaces only the exact top-level <c># Unreleased</c> heading without consuming its following blank line, reset-only placeholder
    /// lines directly before their matching section markers, and two known narrative phrases using ordinal matching.
    /// Variants in casing or wording are left unchanged. Output is deterministic apart from the supplied version and date, uses
    /// <see cref="Environment.NewLine"/> for generated sections, and trims trailing whitespace from the source body. Callers should run
    /// release readiness checks first because duplicate headings, missing phrases, or concurrently edited Markdown are not treated as errors.
    /// </remarks>
    internal static string Build(SemVer version, DateOnly date, string unreleased)
    {
        Markdown.Parse(unreleased);
        var body = Regex.Replace(unreleased, "^#[ \\t]+Unreleased[ \\t]*\\r?$", $"# Release {version}", RegexOptions.Multiline);
        body = body.Replace("living release note for the next coordinated AppSurface version", $"release note for AppSurface {version}", StringComparison.Ordinal);
        body = body.Replace("provisional until a tag is cut", $"finalized on {date:yyyy-MM-dd}", StringComparison.Ordinal);
        foreach (var placeholder in UnreleasedTemplatePlaceholderDefinitions)
        {
            var templateLinePattern = $"^{Regex.Escape(placeholder.Text)}\\r?\\n(?=\\r?\\n<!-- appsurface:unreleased-entries section=\"{placeholder.Section}\" -->)";
            body = Regex.Replace(body, templateLinePattern, string.Empty, RegexOptions.CultureInvariant | RegexOptions.Multiline);
        }

        var header = $"""
            <!--
            Generated by ./eng/release prepare.
            Version: {version}
            Date: {date:yyyy-MM-dd}
            -->

            """;
        return header + body.TrimEnd() + Environment.NewLine;
    }

    /// <summary>
    /// Creates the next-cycle unreleased proof artifact.
    /// </summary>
    /// <param name="previousVersion">Version that just moved into tagged release files.</param>
    /// <returns>Canonical unreleased Markdown for the next cycle, including the previous version reference and a trailing newline.</returns>
    /// <remarks>
    /// This reset intentionally discards the prior living-release body after it has been copied into a tagged release note. It preserves
    /// the expected section order for future checks: overview, shaping work, included changes, and migration watch.
    /// </remarks>
    internal static string ResetUnreleased(SemVer previousVersion)
    {
        return $"""
            # Unreleased

            This is the living release note for the next coordinated AppSurface version after `{previousVersion}`. It stays provisional until the next tag is cut.

            ## What is taking shape

            {TakingShapePlaceholder}

            <!-- appsurface:unreleased-entries section="taking-shape" -->

            ## Included in the next coordinated version

            ### Release and docs surface

            {IncludedChangesPlaceholder}

            <!-- appsurface:unreleased-entries section="included" -->

            ## Migration watch

            {MigrationWatchPlaceholder}

            <!-- appsurface:unreleased-entries section="migration-watch" -->

            """;
    }

    /// <summary>
    /// Builds the tree-local pointer used by coordinated package and documentation links.
    /// </summary>
    /// <param name="version">The immutable tagged release selected by this pointer.</param>
    /// <returns>Deterministic Markdown that links to the exact release note.</returns>
    /// <remarks>
    /// Do not replace this link with a global release lookup. Release archives copy this file into their immutable exact trees;
    /// a historical <c>current</c> route must therefore point to the release that was current when that tree was published.
    /// </remarks>
    internal static string BuildCurrentReleasePointer(SemVer version)
    {
        return ReleaseCurrentPointer.Build(version);
    }
}
