using ForgeTrust.AppSurface.Core;

namespace ForgeTrust.AppSurface.Cli.Tests;

public sealed class AppSurfaceCliReadmeContractTests
{
    [Fact]
    public void Readme_Should_CrossReference_StaticWebsiteDeploymentExtras_Boundary()
    {
        var readme = File.ReadAllText(GetAppSurfaceCliReadmePath());

        Assert.Contains("Static website deployment extras", readme, StringComparison.Ordinal);
        Assert.Contains("../../Web/ForgeTrust.RazorWire.Cli/README.md#static-website-deployment-extras", readme, StringComparison.Ordinal);
        Assert.Contains("opaque files such as `CNAME` belong in the deployment publish root through `--publish-root-extras ./deploy/export-extras.yml`", readme, StringComparison.Ordinal);
        Assert.Contains("RazorWire `RWEXPORT007`", readme, StringComparison.Ordinal);
        Assert.Contains("exporter-owned provider artifacts such as `_redirects` are generated by the exporter", readme, StringComparison.Ordinal);
        Assert.Contains("`appsurface docs export` intentionally does not expose `--publish-root-extras`.", readme, StringComparison.Ordinal);
        Assert.Contains("`.appsurface-docs-route-manifest.json` and `.appsurface-docs-release-manifest.json` describe the files that belong to the archive", readme, StringComparison.Ordinal);
        Assert.Contains("surrounding publish root", readme, StringComparison.Ordinal);
        Assert.Contains("immutable exact release archives", readme, StringComparison.Ordinal);
        Assert.Contains("do not copy `/_redirects` or `/_headers`", readme, StringComparison.Ordinal);
    }

    [Fact]
    public void Readme_Should_Document_Export_Redirect_Boundary()
    {
        var readme = File.ReadAllText(GetAppSurfaceCliReadmePath());

        Assert.Contains("Exporter-managed artifact fetches handle redirects inside the shared engine before response content is read or written", readme, StringComparison.Ordinal);
        Assert.Contains("cross-origin or cross-path artifact redirects fail with RazorWire `RWEXPORT008`", readme, StringComparison.Ordinal);
        Assert.Contains("for `RWEXPORT008`, keep exporter-managed artifact redirects on the same scheme, host, port, and app path", readme, StringComparison.Ordinal);
        Assert.Contains("model the destination as an external reference instead of a static artifact", readme, StringComparison.Ordinal);
    }

    [Fact]
    public void Readme_Should_CrossReference_HybridHostingGuide()
    {
        var readme = File.ReadAllText(GetAppSurfaceCliReadmePath());

        Assert.Contains("../../Web/ForgeTrust.RazorWire/Docs/hybrid-hosting.md", readme, StringComparison.Ordinal);
        Assert.Contains("Cloud Run live-origin recipe", readme, StringComparison.Ordinal);
        Assert.Contains("first-interaction cold-start tradeoff", readme, StringComparison.Ordinal);
        Assert.Contains("appsurface docs export \\", readme, StringComparison.Ordinal);
        Assert.Contains("--public-origin https://docs.example.com", readme, StringComparison.Ordinal);
        Assert.Contains("--live-origin https://api.example.com", readme, StringComparison.Ordinal);
        Assert.Contains("lazy anti-forgery refresh", readme, StringComparison.Ordinal);
    }

    [Fact]
    public void Readme_Should_Document_CoverageRun_PublicConsumerPath()
    {
        var readme = File.ReadAllText(GetAppSurfaceCliReadmePath());

        Assert.Contains("### `appsurface coverage run`", readme, StringComparison.Ordinal);
        Assert.Contains("### `appsurface coverage merge`", readme, StringComparison.Ordinal);
        Assert.Contains("dotnet tool run appsurface coverage run --solution ./MyApp.slnx --dry-run", readme, StringComparison.Ordinal);
        Assert.Contains("dotnet tool run appsurface coverage merge --source ./TestResults/coverage-shards --output ./TestResults/coverage-merged", readme, StringComparison.Ordinal);
        Assert.Contains("dotnet add tests/MyApp.Tests/MyApp.Tests.csproj package coverlet.msbuild", readme, StringComparison.Ordinal);
        Assert.Contains("package-owned ReportGenerator", readme, StringComparison.Ordinal);
        Assert.Contains("`.appsurface-coverage-output`", readme, StringComparison.Ordinal);
        Assert.Contains("Every `ASCOV###` diagnostic includes the problem, likely cause, exact fix, docs anchor, and a log path", readme, StringComparison.Ordinal);
        Assert.Contains("Every merge diagnostic uses the `ASCOV130` through `ASCOV139` range", readme, StringComparison.Ordinal);
        Assert.Contains("| `ASCOV103` | No Coverlet Cobertura files were produced.", readme, StringComparison.Ordinal);
        Assert.Contains("| `ASCOV131` | No `coverage.cobertura.xml` files were found.", readme, StringComparison.Ordinal);
        Assert.Contains("- run: dotnet restore ./MyApp.slnx", readme, StringComparison.Ordinal);
        Assert.Contains("dotnet tool run appsurface coverage run --solution ./MyApp.slnx --configuration Release --no-restore", readme, StringComparison.Ordinal);
        Assert.DoesNotContain("intentionally does not expose run or merge orchestration yet", readme, StringComparison.Ordinal);
    }

    private static string GetAppSurfaceCliReadmePath()
    {
        var repositoryRoot = PathUtils.FindRepositoryRoot(AppContext.BaseDirectory);
        return Path.Join(repositoryRoot, "Cli", "ForgeTrust.AppSurface.Cli", "README.md");
    }
}
