using ForgeTrust.AppSurface.Core;

namespace ForgeTrust.AppSurface.Cli.Tests;

public sealed class AppSurfaceCliReadmeContractTests
{
    [Fact]
    public void Readme_Should_CrossReference_StaticWebsiteDeploymentExtras_Boundary()
    {
        var readme = File.ReadAllText(GetAppSurfaceCliReadmePath());

        Assert.Contains("Static website deployment extras", readme, StringComparison.Ordinal);
        Assert.Contains("../../Web/ForgeTrust.RazorWire.Cli/README.md#static-website-deployment-extras", readme, StringComparison.Ordinal);
        Assert.Contains("opaque files such as `CNAME` belong in the deployment publish root after export", readme, StringComparison.Ordinal);
        Assert.Contains("exporter-owned provider artifacts such as `_redirects` are generated by the exporter", readme, StringComparison.Ordinal);
        Assert.Contains("`.appsurface-docs-release-manifest.json` is written and pinned", readme, StringComparison.Ordinal);
        Assert.Contains("surrounding publish root", readme, StringComparison.Ordinal);
        Assert.Contains("immutable exact release archives", readme, StringComparison.Ordinal);
    }

    private static string GetAppSurfaceCliReadmePath()
    {
        var repositoryRoot = PathUtils.FindRepositoryRoot(AppContext.BaseDirectory);
        return Path.Join(repositoryRoot, "Cli", "ForgeTrust.AppSurface.Cli", "README.md");
    }
}
