<Project>
    <PropertyGroup>
        <BaseIntermediateOutputPath>obj/$(MSBuildProjectName)/</BaseIntermediateOutputPath>
        <MSBuildProjectExtensionsPath>$(BaseIntermediateOutputPath)</MSBuildProjectExtensionsPath>
        <BaseOutputPath>bin/$(MSBuildProjectName)/</BaseOutputPath>
    </PropertyGroup>
</Project>
