#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd -- "${script_dir}/.." && pwd)"

dotnet run --project "${repo_root}/tools/ForgeTrust.AppSurface.Release/ForgeTrust.AppSurface.Release.csproj" -- "$@"
