"""Closed N09 detached-record checks. Never establishes native qualification."""
import json

MAX_WORKER_BYTES = 4096
PHASE_FRAME = {"schema": "issue779-cancellation-phase-v1", "case": "N09",
               "phase": "BeforeActivation", "native_authority": False}
TERMINAL = (b"ASEVD409: Fresh output allocation or activation failed. Fix: use an explicit mode "
            b"and supported protected worker. See start-here/evidencehost.md.\n")


class Rejected(ValueError):
    """Fixed rejection without embedding supplied data."""


def _pairs(pairs):
    result, folded = {}, set()
    for key, value in pairs:
        if key.casefold() in folded:
            raise Rejected("n09-record-rejected")
        folded.add(key.casefold())
        result[key] = value
    return result


def _line(raw, keys, maximum_bytes=1024):
    if type(raw) is not bytes or not 1 < len(raw) <= maximum_bytes or not raw.endswith(b"\n") or raw.count(b"\n") != 1:
        raise Rejected("n09-record-rejected")
    value = json.loads(raw[:-1].decode("utf-8", "strict"), object_pairs_hook=_pairs,
                       parse_constant=lambda _: (_ for _ in ()).throw(Rejected("n09-record-rejected")))
    if type(value) is not dict or set(value) != set(keys):
        raise Rejected("n09-record-rejected")
    return value


def check_worker(raw):
    """Check complete original worker bytes and exact N09 cancellation semantics."""
    try:
        if type(raw) is not bytes or not 0 < len(raw) <= MAX_WORKER_BYTES:
            raise Rejected("n09-record-rejected")
        lines = raw.splitlines(keepends=True)
        if len(lines) != 4 or b"".join(lines) != raw or lines[-1] != TERMINAL:
            raise Rejected("n09-record-rejected")
        phase = _line(lines[0], PHASE_FRAME)
        if phase != PHASE_FRAME or type(phase["native_authority"]) is not bool or phase["native_authority"] is not False:
            raise Rejected("n09-record-rejected")
        allocation = _line(lines[1], ("phase", "operation", "stageOutcome", "terminalCode", "errorClass", "nativeErrno", "schema"))
        if allocation != {"schema": "evidence-allocation-failure-v1", "phase": "BeforeActivation",
                          "operation": "Completed", "stageOutcome": "Cancelled", "terminalCode": "CallerCancelled",
                          "errorClass": "Cancelled", "nativeErrno": None}:
            raise Rejected("n09-record-rejected")
        cancelled = _line(lines[2], ("case", "phase", "callerTokenCancelled", "lifecycleCallerCancelled",
                                      "ownWorkStopped", "schema", "nativeAuthority"))
        if cancelled != {"schema": "issue779-original-cancellation-v1", "case": "N09",
                         "phase": "BeforeActivation", "callerTokenCancelled": True,
                         "lifecycleCallerCancelled": True, "ownWorkStopped": True, "nativeAuthority": False} or any(
                         type(cancelled[key]) is not bool for key in
                         ("callerTokenCancelled", "lifecycleCallerCancelled", "ownWorkStopped", "nativeAuthority")):
            raise Rejected("n09-record-rejected")
        return {"schema": "issue779-n09-record-consistency-v1", "case": "N09",
                "phase": "BeforeActivation", "native_authority": False, "native_acceptance": False}
    except (Rejected, ValueError, TypeError, KeyError, UnicodeError, RecursionError):
        raise Rejected("n09-record-rejected") from None



def check_allocation_slot_record(raw, *, generation):
    """Parse the exact root-owned N09 slot line as untrusted consistency data only.

    Does not establish that a path was generated by the root workspace, that native
    descriptors were actually retained/closed, or that accounts/cgroups were cleaned.
    The native runner must independently compare these identities with live root-owned
    observations taken from the fixed generated workspace and retain terminal custody facts.
    """
    try:
        keys = ("schema", "generation", "output_parent_before_signal", "output_parent_after_join",
                "allocated_slot_before_signal", "allocated_slot_after_join", "slot_empty_before_signal",
                "slot_empty_after_worker_join", "parent_handle_closed", "slot_handle_closed",
                "observation_only", "native_authority", "native_acceptance")
        value = _line(raw, keys, maximum_bytes=2048)
        if value["schema"] != "issue779-n09-allocation-slot-observation-v1" or value["generation"] != generation:
            raise Rejected("n09-record-rejected")
        identity_keys = ("DeviceMajor", "DeviceMinor", "Inode", "Uid", "Gid", "Mode")
        names = ("output_parent_before_signal", "output_parent_after_join",
                 "allocated_slot_before_signal", "allocated_slot_after_join")
        identities = {}
        limits = {"DeviceMajor": 0xffffffff, "DeviceMinor": 0xffffffff, "Inode": 0xffffffffffffffff,
                  "Uid": 0xffffffff, "Gid": 0xffffffff, "Mode": 0xffff}
        for name in names:
            item = value[name]
            if type(item) is not dict or set(item) != set(identity_keys):
                raise Rejected("n09-record-rejected")
            for key, limit in limits.items():
                if type(item[key]) is not int or item[key] < 0 or item[key] > limit:
                    raise Rejected("n09-record-rejected")
            if item["Inode"] == 0:
                raise Rejected("n09-record-rejected")
            identities[name] = item
        parent_before, parent_after = identities[names[0]], identities[names[1]]
        slot_before, slot_after = identities[names[2]], identities[names[3]]
        if parent_before != parent_after or slot_before != slot_after:
            raise Rejected("n09-record-rejected")
        if (parent_before["DeviceMajor"], parent_before["DeviceMinor"]) != (slot_before["DeviceMajor"], slot_before["DeviceMinor"]):
            raise Rejected("n09-record-rejected")
        if parent_before["Inode"] == slot_before["Inode"] or parent_before["Uid"] == 0 or parent_before["Gid"] == 0:
            raise Rejected("n09-record-rejected")
        if (slot_before["Uid"], slot_before["Gid"]) != (parent_before["Uid"], parent_before["Gid"]):
            raise Rejected("n09-record-rejected")
        if parent_before["Mode"] != 0x41c0 or slot_before["Mode"] != 0x41c0:
            raise Rejected("n09-record-rejected")
        booleans = ("slot_empty_before_signal", "slot_empty_after_worker_join", "parent_handle_closed",
                    "slot_handle_closed", "observation_only", "native_authority", "native_acceptance")
        if any(type(value[key]) is not bool for key in booleans):
            raise Rejected("n09-record-rejected")
        if any(value[key] is not True for key in booleans[:5]) or any(value[key] is not False for key in booleans[5:]):
            raise Rejected("n09-record-rejected")
        return {"schema": "issue779-n09-allocation-record-consistency-v1", "generation": generation,
                "identities": identities, "native_authority": False, "native_acceptance": False}
    except (Rejected, ValueError, TypeError, KeyError, UnicodeError, RecursionError):
        raise Rejected("n09-record-rejected") from None




def check_root_cleanup_record(raw, *, generation):
    """Validate the source-owned final cleanup line as consistency data only."""
    try:
        keys = ("schema", "generation", "results_gid", "accounts_closed", "root_custody_closed",
                "original_owners_closed", "observation_only", "native_authority", "native_acceptance")
        value = _line(raw, keys, maximum_bytes=1024)
        if (value["schema"] != "issue779-cancellation-root-cleanup-v1"
                or value["generation"] != generation
                or type(value["results_gid"]) is not int or value["results_gid"] <= 0
                or value["results_gid"] >= 0xffffffff):
            raise Rejected("n09-record-rejected")
        bools = ("accounts_closed", "root_custody_closed", "original_owners_closed",
                 "observation_only", "native_authority", "native_acceptance")
        if any(type(value[key]) is not bool for key in bools):
            raise Rejected("n09-record-rejected")
        if any(value[key] is not True for key in bools[:4]) or any(value[key] is not False for key in bools[4:]):
            raise Rejected("n09-record-rejected")
        return {"schema": value["schema"], "generation": generation, "results_gid": value["results_gid"],
                "accounts_closed": True, "root_custody_closed": True, "original_owners_closed": True,
                "native_authority": False, "native_acceptance": False}
    except (Rejected, ValueError, TypeError, KeyError, UnicodeError, RecursionError):
        raise Rejected("n09-record-rejected") from None


def split_root_stderr(raw, *, generation):
    """Split the exact seven-line N09 stderr projection into source records.

    Order is allocation-slot, signal, kernel, joined streams, first failure,
    final cleanup, and the fixed ASEVD410 message. Parsed records are consistency
    data only; callers still establish actual process/cgroup/EOF and filesystem facts.
    """
    try:
        if type(raw) is not bytes or not 0 < len(raw) <= 114688:
            raise Rejected("n09-record-rejected")
        lines = raw.splitlines(keepends=True)
        if b"".join(lines) != raw or len(lines) != 7 or any(not x.endswith(b"\n") for x in lines):
            raise Rejected("n09-record-rejected")
        slot = check_allocation_slot_record(lines[0], generation=generation)
        cleanup = check_root_cleanup_record(lines[5], generation=generation)
        if lines[6] != TERMINAL:
            raise Rejected("n09-record-rejected")
        return {"slot_record": slot, "original_root_lines": (lines[1], lines[2], lines[3], lines[4], lines[6]),
                "cleanup_record": cleanup, "native_authority": False, "native_acceptance": False}
    except (Rejected, ValueError, TypeError, KeyError, UnicodeError, RecursionError):
        raise Rejected("n09-record-rejected") from None


def verify_post_settlement_paths(*, generation, expected_worker_uid, expected_worker_gid, parsed_slot):
    """Independently sample the generated Linux paths after original root exit.

    This is an OS-side comparison with untrusted source JSON, not native acceptance.
    The caller must already have verified the original root/worker process and their
    selected cgroups are settled; this function does not infer that from JSON.
    """
    import os, stat
    if (type(generation) is not str or len(generation) != 32
            or any(c not in "0123456789abcdef" for c in generation)
            or type(expected_worker_uid) is not int or type(expected_worker_gid) is not int
            or expected_worker_uid <= 0 or expected_worker_gid <= 0
            or type(parsed_slot) is not dict or parsed_slot.get("generation") != generation):
        raise Rejected("n09-record-rejected")
    identities = parsed_slot.get("identities")
    if type(identities) is not dict:
        raise Rejected("n09-record-rejected")
    parent_expected = identities.get("output_parent_after_join")
    slot_expected = identities.get("allocated_slot_after_join")
    flags = os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW | os.O_CLOEXEC
    opened = []
    try:
        runfd = os.open("/run", flags); opened.append(runfd)
        runst = os.fstat(runfd)
        if not stat.S_ISDIR(runst.st_mode) or runst.st_uid != 0 or stat.S_IMODE(runst.st_mode) & 0o022:
            raise Rejected("n09-record-rejected")
        wsfd = os.open("appsurface-evidence-" + generation, flags, dir_fd=runfd); opened.append(wsfd)
        ws = os.fstat(wsfd)
        if not stat.S_ISDIR(ws.st_mode) or ws.st_uid != 0 or ws.st_gid <= 0 or stat.S_IMODE(ws.st_mode) != 0o750:
            raise Rejected("n09-record-rejected")
        outfd = os.open("output", flags, dir_fd=wsfd); opened.append(outfd)
        slotfd = os.open("evidence", flags, dir_fd=outfd); opened.append(slotfd)
        parent = os.fstat(outfd); slot = os.fstat(slotfd)
        def shape(st, expected):
            return (stat.S_ISDIR(st.st_mode) and stat.S_IMODE(st.st_mode) == 0o700
                    and st.st_uid == expected_worker_uid and st.st_gid == expected_worker_gid
                    and os.major(st.st_dev) == expected["DeviceMajor"]
                    and os.minor(st.st_dev) == expected["DeviceMinor"]
                    and st.st_ino == expected["Inode"] and st.st_uid == expected["Uid"]
                    and st.st_gid == expected["Gid"] and st.st_mode == expected["Mode"])
        if (not shape(parent, parent_expected) or not shape(slot, slot_expected)
                or os.listdir(outfd) != ["evidence"] or os.listdir(slotfd) != []):
            raise Rejected("n09-record-rejected")
        return {"schema": "issue779-n09-post-settlement-path-comparison-v1",
                "parent_identity_matches": True, "slot_identity_matches": True,
                "slot_empty": True, "native_authority": False, "native_acceptance": False}
    except (OSError, ValueError, TypeError, KeyError, OverflowError):
        raise Rejected("n09-record-rejected") from None
    finally:
        for fd in reversed(opened):
            try: os.close(fd)
            except OSError: pass
