using System.Globalization;
using System.Text;
using Npgsql;

namespace ForgeTrust.AppSurface.Durable.PostgreSql;

/// <summary>
/// Implements explicit, package-owned durable schema operations for PostgreSQL.
/// </summary>
public sealed class PostgreSqlDurableRuntimeSchemaManager : IDurableRuntimeSchemaManager
{
    private const long MigrationAdvisoryLock = 0x415344555241424C; // "ASDURABL"
    private readonly NpgsqlDataSource _dataSource;
    private readonly IReadOnlyList<DurablePostgreSqlMigration> _migrations;

    /// <summary>
    /// Initializes a schema manager using a migration-role data source.
    /// </summary>
    /// <param name="dataSource">Data source whose role is authorized to own and migrate the durable schema.</param>
    public PostgreSqlDurableRuntimeSchemaManager(NpgsqlDataSource dataSource)
    {
        _dataSource = dataSource ?? throw new ArgumentNullException(nameof(dataSource));
        _migrations = DurablePostgreSqlMigrationCatalog.Load();
    }

    /// <summary>
    /// Gets the schema version required by this package.
    /// </summary>
    public static int RequiredVersion => DurablePostgreSqlMigrationCatalog.Load().Count;

    /// <inheritdoc />
    public async ValueTask<DurableRuntimeSchemaStatus> GetStatusAsync(CancellationToken cancellationToken = default)
    {
        await using var connection = await _dataSource.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
        return await ReadStatusAsync(connection, cancellationToken).ConfigureAwait(false);
    }

    /// <inheritdoc />
    public string GenerateScript(int fromVersion = 0)
    {
        if (fromVersion < 0 || fromVersion > _migrations.Count)
        {
            throw new ArgumentOutOfRangeException(
                nameof(fromVersion),
                fromVersion,
                $"The source version must be between 0 and {_migrations.Count}.");
        }

        var builder = new StringBuilder();
        builder.AppendLine("-- Generated by ForgeTrust.AppSurface.Durable.PostgreSql.");
        builder.AppendLine("-- Apply with the migration owner. Application runtime roles must not execute this script.");
        builder.Append("SELECT pg_advisory_lock(")
            .Append(MigrationAdvisoryLock.ToString(CultureInfo.InvariantCulture))
            .AppendLine(");");

        foreach (var migration in _migrations.Where(migration => migration.Version > fromVersion))
        {
            AppendMigrationScript(builder, migration);
        }

        builder.Append("SELECT pg_advisory_unlock(")
            .Append(MigrationAdvisoryLock.ToString(CultureInfo.InvariantCulture))
            .AppendLine(");");
        return builder.ToString();
    }

    /// <inheritdoc />
    public async ValueTask<DurableRuntimeSchemaApplyResult> ApplyAsync(CancellationToken cancellationToken = default)
    {
        await using var connection = await _dataSource.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
        await AcquireMigrationLockAsync(connection, cancellationToken).ConfigureAwait(false);
        try
        {
            var before = await ReadStatusAsync(connection, cancellationToken).ConfigureAwait(false);
            if (before.Compatibility is DurableRuntimeSchemaCompatibility.Inconsistent or DurableRuntimeSchemaCompatibility.StoreTooNew)
            {
                throw new DurableRuntimeSchemaException(before);
            }

            var applied = new List<int>();
            foreach (var migration in _migrations.Where(migration => migration.Version > before.InstalledVersion))
            {
                await ApplyMigrationAsync(connection, migration, cancellationToken).ConfigureAwait(false);
                applied.Add(migration.Version);
            }

            var after = await ReadStatusAsync(connection, cancellationToken).ConfigureAwait(false);
            if (!after.IsCompatible)
            {
                throw new DurableRuntimeSchemaException(after);
            }

            return new DurableRuntimeSchemaApplyResult(before.InstalledVersion, after.InstalledVersion, applied);
        }
        finally
        {
            await ReleaseMigrationLockAsync(connection).ConfigureAwait(false);
        }
    }

    /// <inheritdoc />
    public async ValueTask ValidateAsync(CancellationToken cancellationToken = default)
    {
        var status = await GetStatusAsync(cancellationToken).ConfigureAwait(false);
        if (!status.IsCompatible)
        {
            throw new DurableRuntimeSchemaException(status);
        }
    }

    /// <inheritdoc />
    public async ValueTask<DurableRuntimeEpochRotationResult> RotateRuntimeEpochAsync(
        Guid expectedActiveEpoch,
        Guid newActiveEpoch,
        string actorId,
        string reasonCode,
        CancellationToken cancellationToken = default)
    {
        if (expectedActiveEpoch == Guid.Empty)
        {
            throw new ArgumentException("The expected active runtime epoch must not be empty.", nameof(expectedActiveEpoch));
        }

        if (newActiveEpoch == Guid.Empty || newActiveEpoch == expectedActiveEpoch)
        {
            throw new ArgumentException("The new runtime epoch must be non-empty and different.", nameof(newActiveEpoch));
        }

        actorId = RequireOperatorCode(actorId, nameof(actorId), 200);
        reasonCode = RequireOperatorCode(reasonCode, nameof(reasonCode), 120);
        await ValidateAsync(cancellationToken).ConfigureAwait(false);
        await using var connection = await _dataSource.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
        await using var transaction = await connection.BeginTransactionAsync(cancellationToken).ConfigureAwait(false);
        try
        {
            const string sql = """
                WITH rotated AS
                (
                    UPDATE appsurface_durable.store_metadata
                    SET active_runtime_epoch = @new_epoch,
                        updated_at = clock_timestamp()
                    WHERE singleton
                      AND active_runtime_epoch = @expected_epoch
                    RETURNING active_runtime_epoch, updated_at
                ),
                historied AS
                (
                    INSERT INTO appsurface_durable.runtime_epoch_history
                        (previous_epoch, active_epoch, actor_id, reason_code, observed_at)
                    SELECT @expected_epoch, active_runtime_epoch, @actor_id, @reason_code, updated_at
                    FROM rotated
                    RETURNING active_epoch, observed_at
                )
                SELECT active_epoch, observed_at
                FROM historied;
                """;
            await using var command = new NpgsqlCommand(sql, connection, transaction);
            command.Parameters.AddWithValue("expected_epoch", expectedActiveEpoch);
            command.Parameters.AddWithValue("new_epoch", newActiveEpoch);
            command.Parameters.AddWithValue("actor_id", actorId);
            command.Parameters.AddWithValue("reason_code", reasonCode);
            await using var reader = await command.ExecuteReaderAsync(cancellationToken).ConfigureAwait(false);
            if (!await reader.ReadAsync(cancellationToken).ConfigureAwait(false))
            {
                throw new InvalidOperationException(
                    $"{DurableProblemCodes.RecoveryEpochRequired}: The expected recovery epoch is not currently active; reload deployment state before rotating.");
            }

            var active = reader.GetGuid(0);
            var rotatedAt = new DateTimeOffset(reader.GetFieldValue<DateTime>(1), TimeSpan.Zero);
            await reader.CloseAsync().ConfigureAwait(false);
            await transaction.CommitAsync(cancellationToken).ConfigureAwait(false);
            return new DurableRuntimeEpochRotationResult(expectedActiveEpoch, active, rotatedAt);
        }
        catch
        {
            await transaction.RollbackAsync(CancellationToken.None).ConfigureAwait(false);
            throw;
        }
    }

    private static string RequireOperatorCode(string value, string parameterName, int maximumLength)
    {
        if (string.IsNullOrWhiteSpace(value)
            || value.Length > maximumLength
            || value.Any(static character =>
                !char.IsAsciiLetterOrDigit(character)
                && character is not '-' and not '_' and not '.' and not ':'))
        {
            throw new ArgumentException(
                "Operator identifiers must use the durable opaque-code grammar.",
                parameterName);
        }

        return value;
    }

    private async ValueTask<DurableRuntimeSchemaStatus> ReadStatusAsync(
        NpgsqlConnection connection,
        CancellationToken cancellationToken)
    {
        const string existenceSql = """
            SELECT
                to_regnamespace('appsurface_durable') IS NOT NULL,
                to_regclass('appsurface_durable.schema_migration') IS NOT NULL;
            """;
        await using var existenceCommand = new NpgsqlCommand(existenceSql, connection);
        await using var existenceReader = await existenceCommand.ExecuteReaderAsync(cancellationToken).ConfigureAwait(false);
        await existenceReader.ReadAsync(cancellationToken).ConfigureAwait(false);
        var schemaExists = existenceReader.GetBoolean(0);
        var migrationTableExists = existenceReader.GetBoolean(1);
        await existenceReader.CloseAsync().ConfigureAwait(false);

        if (!schemaExists && !migrationTableExists)
        {
            return CreateStatus(DurableRuntimeSchemaCompatibility.Missing, 0, [], "The durable schema is not installed.");
        }

        if (!schemaExists || !migrationTableExists)
        {
            return CreateStatus(
                DurableRuntimeSchemaCompatibility.Inconsistent,
                0,
                [],
                "The appsurface_durable schema exists without complete package migration metadata.");
        }

        const string migrationSql = """
            SELECT version, name, sha256
            FROM appsurface_durable.schema_migration
            ORDER BY version;
            """;
        var applied = new List<AppliedMigration>();
        await using (var migrationCommand = new NpgsqlCommand(migrationSql, connection))
        await using (var reader = await migrationCommand.ExecuteReaderAsync(cancellationToken).ConfigureAwait(false))
        {
            while (await reader.ReadAsync(cancellationToken).ConfigureAwait(false))
            {
                applied.Add(new AppliedMigration(reader.GetInt32(0), reader.GetString(1), reader.GetString(2)));
            }
        }

        var installedVersion = applied.Count == 0 ? 0 : applied[^1].Version;
        var integrityProblem = FindIntegrityProblem(applied);
        if (integrityProblem is not null)
        {
            return CreateStatus(
                DurableRuntimeSchemaCompatibility.Inconsistent,
                installedVersion,
                applied.Select(item => item.Version).ToArray(),
                integrityProblem);
        }

        const string metadataSql = """
            SELECT schema_version,
                   minimum_reader_version,
                   maximum_reader_version,
                   minimum_writer_version,
                   maximum_writer_version
            FROM appsurface_durable.store_metadata
            WHERE singleton;
            """;
        await using var metadataCommand = new NpgsqlCommand(metadataSql, connection);
        StoreCompatibilityRange? range = null;
        await using (var metadataReader = await metadataCommand.ExecuteReaderAsync(cancellationToken).ConfigureAwait(false))
        {
            if (await metadataReader.ReadAsync(cancellationToken).ConfigureAwait(false))
            {
                range = new StoreCompatibilityRange(
                    metadataReader.GetInt32(0),
                    metadataReader.GetInt32(1),
                    metadataReader.GetInt32(2),
                    metadataReader.GetInt32(3),
                    metadataReader.GetInt32(4));
            }
        }

        if (range is null || range.SchemaVersion != installedVersion || !range.IsValid)
        {
            return CreateStatus(
                DurableRuntimeSchemaCompatibility.Inconsistent,
                installedVersion,
                applied.Select(item => item.Version).ToArray(),
                "Store metadata does not match the recorded migration sequence.");
        }

        var runtimeVersion = _migrations.Count;
        var compatibility = installedVersion switch
        {
            var version when version < runtimeVersion => DurableRuntimeSchemaCompatibility.UpgradeRequired,
            _ when range.Allows(runtimeVersion) => DurableRuntimeSchemaCompatibility.Compatible,
            _ => DurableRuntimeSchemaCompatibility.StoreTooNew,
        };
        var problem = compatibility switch
        {
            DurableRuntimeSchemaCompatibility.Compatible => null,
            DurableRuntimeSchemaCompatibility.UpgradeRequired => "Apply the pending package migrations before starting workers.",
            _ => "Upgrade the runtime package to one that supports the installed store version.",
        };
        return CreateStatus(
            compatibility,
            installedVersion,
            applied.Select(item => item.Version).ToArray(),
            problem,
            range.MinimumReaderVersion,
            range.MaximumReaderVersion,
            range.MinimumWriterVersion,
            range.MaximumWriterVersion);
    }

    private DurableRuntimeSchemaStatus CreateStatus(
        DurableRuntimeSchemaCompatibility compatibility,
        int installedVersion,
        IReadOnlyList<int> appliedVersions,
        string? problem,
        int minimumReaderVersion = 0,
        int maximumReaderVersion = 0,
        int minimumWriterVersion = 0,
        int maximumWriterVersion = 0)
    {
        var pending = _migrations
            .Where(migration => migration.Version > installedVersion)
            .Select(migration => migration.Version)
            .ToArray();
        return new DurableRuntimeSchemaStatus(
            compatibility,
            installedVersion,
            _migrations.Count,
            minimumReaderVersion,
            maximumReaderVersion,
            minimumWriterVersion,
            maximumWriterVersion,
            appliedVersions,
            pending,
            problem);
    }

    private string? FindIntegrityProblem(IReadOnlyList<AppliedMigration> applied)
    {
        for (var index = 0; index < applied.Count; index++)
        {
            var actual = applied[index];
            var expectedVersion = index + 1;
            if (actual.Version != expectedVersion)
            {
                return $"Migration history is not contiguous at version {expectedVersion}.";
            }

            if (actual.Version > _migrations.Count)
            {
                continue;
            }

            var expected = _migrations[actual.Version - 1];
            if (!StringComparer.Ordinal.Equals(actual.Name, expected.Name) ||
                !StringComparer.OrdinalIgnoreCase.Equals(actual.Sha256, expected.Sha256))
            {
                return $"Recorded migration {actual.Version:D4} does not match the package resource.";
            }
        }

        return null;
    }

    private static async ValueTask AcquireMigrationLockAsync(
        NpgsqlConnection connection,
        CancellationToken cancellationToken)
    {
        await using var command = new NpgsqlCommand("SELECT pg_advisory_lock(@lock_id);", connection);
        command.Parameters.AddWithValue("lock_id", MigrationAdvisoryLock);
        await command.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
    }

    private static async ValueTask ReleaseMigrationLockAsync(NpgsqlConnection connection)
    {
        try
        {
            await using var command = new NpgsqlCommand("SELECT pg_advisory_unlock(@lock_id);", connection);
            command.Parameters.AddWithValue("lock_id", MigrationAdvisoryLock);
            await command.ExecuteNonQueryAsync(CancellationToken.None).ConfigureAwait(false);
        }
        catch (NpgsqlException)
        {
            // Closing the physical session releases a session-level advisory lock. Preserve the original failure.
        }
    }

    private async ValueTask ApplyMigrationAsync(
        NpgsqlConnection connection,
        DurablePostgreSqlMigration migration,
        CancellationToken cancellationToken)
    {
        await using var transaction = await connection.BeginTransactionAsync(cancellationToken).ConfigureAwait(false);
        try
        {
            await using (var migrationCommand = new NpgsqlCommand(migration.Sql, connection, transaction))
            {
                await migrationCommand.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
            }

            const string metadataSql = """
                INSERT INTO appsurface_durable.schema_migration (version, name, sha256)
                VALUES (@version, @name, @sha256);

                UPDATE appsurface_durable.store_metadata
                SET schema_version = @version,
                    minimum_reader_version = 1,
                    maximum_reader_version = @version,
                    minimum_writer_version = 1,
                    maximum_writer_version = @version,
                    updated_at = clock_timestamp()
                WHERE singleton;
                """;
            await using var metadataCommand = new NpgsqlCommand(metadataSql, connection, transaction);
            metadataCommand.Parameters.AddWithValue("version", migration.Version);
            metadataCommand.Parameters.AddWithValue("name", migration.Name);
            metadataCommand.Parameters.AddWithValue("sha256", migration.Sha256);
            await metadataCommand.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
            await transaction.CommitAsync(cancellationToken).ConfigureAwait(false);
        }
        catch
        {
            await transaction.RollbackAsync(CancellationToken.None).ConfigureAwait(false);
            throw;
        }
    }

    private static void AppendMigrationScript(StringBuilder builder, DurablePostgreSqlMigration migration)
    {
        builder.AppendLine();
        builder.Append("-- Migration ").Append(migration.Version.ToString("D4", CultureInfo.InvariantCulture))
            .Append('_').AppendLine(migration.Name);
        builder.AppendLine("BEGIN;");
        builder.Append(migration.Sql);
        builder.AppendLine();
        builder.Append("INSERT INTO appsurface_durable.schema_migration (version, name, sha256) VALUES (")
            .Append(migration.Version.ToString(CultureInfo.InvariantCulture)).Append(", '")
            .Append(EscapeSqlLiteral(migration.Name)).Append("', '")
            .Append(EscapeSqlLiteral(migration.Sha256)).AppendLine("');");
        builder.Append("UPDATE appsurface_durable.store_metadata SET schema_version = ")
            .Append(migration.Version.ToString(CultureInfo.InvariantCulture))
            .Append(", minimum_reader_version = 1")
            .Append(", maximum_reader_version = ").Append(migration.Version.ToString(CultureInfo.InvariantCulture))
            .Append(", minimum_writer_version = 1")
            .Append(", maximum_writer_version = ").Append(migration.Version.ToString(CultureInfo.InvariantCulture))
            .AppendLine(", updated_at = clock_timestamp() WHERE singleton;");
        builder.AppendLine("COMMIT;");
    }

    private static string EscapeSqlLiteral(string value) => value.Replace("'", "''", StringComparison.Ordinal);

    private sealed record AppliedMigration(int Version, string Name, string Sha256);

    private sealed record StoreCompatibilityRange(
        int SchemaVersion,
        int MinimumReaderVersion,
        int MaximumReaderVersion,
        int MinimumWriterVersion,
        int MaximumWriterVersion)
    {
        internal bool IsValid =>
            SchemaVersion > 0 &&
            MinimumReaderVersion > 0 &&
            MaximumReaderVersion >= MinimumReaderVersion &&
            MaximumReaderVersion <= SchemaVersion &&
            MinimumWriterVersion > 0 &&
            MaximumWriterVersion >= MinimumWriterVersion &&
            MaximumWriterVersion <= SchemaVersion;

        internal bool Allows(int runtimeVersion) =>
            runtimeVersion >= MinimumReaderVersion &&
            runtimeVersion <= MaximumReaderVersion &&
            runtimeVersion >= MinimumWriterVersion &&
            runtimeVersion <= MaximumWriterVersion;
    }
}
