<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ForgeTrust.AppSurface.Cli" />
    <InternalsVisibleTo Include="ForgeTrust.AppSurface.Cli.Tests" />
    <InternalsVisibleTo Include="ForgeTrust.AppSurface.Docs" />
    <InternalsVisibleTo Include="ForgeTrust.AppSurface.Docs.Tests" />
    <InternalsVisibleTo Include="ForgeTrust.AppSurface.Release" />
    <InternalsVisibleTo Include="ForgeTrust.AppSurface.Release.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Markdig" />
  </ItemGroup>
</Project>
